apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project-container
        image: warrparray/project:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  selector:
    app: project
  type: NodePort
  ports:
  - protocol: TCP
    port: 80         # Port your app serves traffic on
    targetPort: 80   # Container port
    nodePort: 30080  # External port to access from outside Minikube (optional, 30000–32767)
