name: Build and Deploy to Minikube via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USER_NAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USER_NAME }}/project:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/project:latest

    - name: Create directory on Contabo server if missing
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CONTABO_HOST }}
        username: ${{ secrets.CONTABO_USER }}
        password: ${{ secrets.CONTABO_PASSWORD }}
        script: mkdir -p /home/${{ secrets.CONTABO_USER }}/project

    - name: Upload deployment.yaml to Contabo server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.CONTABO_HOST }}
        username: ${{ secrets.CONTABO_USER }}
        password: ${{ secrets.CONTABO_PASSWORD }}
        source: "deployment.yaml"
        target: "/home/${{ secrets.CONTABO_USER }}/project/"

    - name: Deploy to Minikube on Contabo server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.CONTABO_HOST }}
        username: ${{ secrets.CONTABO_USER }}
        password: ${{ secrets.CONTABO_PASSWORD }}
        script: |
          echo "Pulling latest image from Docker Hub"
          docker pull ${{ secrets.DOCKER_HUB_USER_NAME }}/project:latest

          echo "Deploying to Minikube"
          kubectl delete deployment project-deploy --ignore-not-found
          kubectl apply -f /home/${{ secrets.CONTABO_USER }}/project/deployment.yaml
